# -*- coding: utf-8 -*-
"""interface.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hZS2QKXz6rzAN37Dpxiwoj4oxcsn4cQU
"""

# interface.py
import gradio as gr
import requests

# Define a Gradio interface function to call the FastAPI endpoint
def classify_text(text):
    # Call the FastAPI endpoint for prediction
    response = requests.post("http://127.0.0.1:8000/predict", json={"text": text})
    if response.status_code == 200:
        result = response.json()
        return f"Sentiment: {result['label']}, Scores: {result['scores']}"
    else:
        return "Error"

# Define the Gradio interface
iface = gr.Interface(
    fn=classify_text,
    inputs="text",
    outputs="text",
    title="PhoBERT Sentiment Analysis",
    description="Enter text to classify sentiment as Positive, Negative, or Neutral."
)

# Launch Gradio
iface.launch()